---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.dekorate.io/vcs-url: <<unknown>>
    app.dekorate.io/commit-id: 208c8ff18235fd621ec4cd84f1ff53c74f6e01dd
  labels:
    app.kubernetes.io/name: ${{values.destination.repo}}
    app.kubernetes.io/part-of: com.adp
    app.kubernetes.io/version: 1.0-SNAPSHOT
    backstage.io/kubernetes-id: ${{values.destination.repo}}
  name: ${{values.destination.repo}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ${{values.destination.repo}}
      app.kubernetes.io/part-of: com.adp
      app.kubernetes.io/version: 1.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.dekorate.io/vcs-url: <<unknown>>
        app.dekorate.io/commit-id: 208c8ff18235fd621ec4cd84f1ff53c74f6e01dd
      labels:
        app.kubernetes.io/name: ${{values.destination.repo}}
        app.kubernetes.io/part-of: com.adp
        app.kubernetes.io/version: 1.0-SNAPSHOT
        backstage.io/kubernetes-id: ${{values.destination.repo}}
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: {{ .Values.app.image }}
          imagePullPolicy: IfNotPresent
          name: ${{values.destination.repo}}
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
