spring:
  application:
    name: ${{values.component_id}}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          #audiences:
          #- api://default
          issuer-uri: https://dev-696450.okta.com/oauth2/default
          jwk-set-uri: https://dev-696450.okta.com/oauth2/default/v1/keys

server:
  error:
    include-message: ALWAYS
    include-stacktrace: NEVER
  servlet:
    context-path: /v1

#######  Logging & Observability ############
# All traces should be sent to latency analysis tool
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include:
          - '*'
        #- dynatrace

  dynatrace:
    metrics:
      export:
        uri: https://xjr50536.live.dynatrace.com/api/v2/metrics/ingest
        api-token: dt0c01.LBEX7GHBLCFDD6YTSVMTHNK6.PQQH3M5GHMPZDJULZHB77XSLRPPXC74VT7OU5LNLBVJSENFXSEWNOVUJVFYWZQNF
        v2:
          metric-key-prefix: ${spring.application.name}

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'


  level:
    root: info
    #org.springframework.security: trace
